### ISSUE TITLE
Please add a bugtracker and home page URL

### ISSUE THREAD

**Issue by pcav** [AdrienVH/ElasticSearchConnector#1]
to metadata.txt, to make collaboration around your plugin easier. This GH address will do well.

**Comment by AdrienVH** [comment]
Edit commited ! Thanks for the tip...

**Comment by pcav** [comment]
Thanks. I still cannot see the URLs in the page http://plugins.qgis.org/plugins/ElasticSearchConnector/

**Comment by AdrienVH** [comment]
Do i need to upload a new version of my plugin to QGIS "Share a plugin" page ?
Cause i just edited my GH repo...

**Comment by pcav** [comment]
Yes, please.

**Comment by AdrienVH** [comment]
Thanls for your help ! It's uploaded :-)

**Comment by pcav** [comment]
Thanks you!
